app: automated-deployment
service: automated-deployment
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  tracing:
    apiGateway: true
    lambda: true

functions:
  hello:
    handler: function.handler
    events:
      - httpApi:
          path: /
          method: get
